### ISSUE TITLE
Proper filename with Restore endpoint

### ISSUE THREAD

**Issue by Naghal** [pqina/react-filepond#122]
### Summary
Hi, I am trying to use the server Restore endpoint to restore a previously uploaded file. The scenario is the following:
A user fill a form where there is an upload component. He uploads a file.
He exits the form without submitting. The files are kept on the server for 7 days and he can go back to the form and start from where he left the last time.

The file restore works, but the displayed name in the Filepond is the server file key instead of the file name. (Ex.: c2lnbmF0dXJlLnBuZw instead of signature.png)

### How to reproduce
Pass the file to restore as prop to the component
`files={[{source: 'c2lnbmF0dXJlLnBuZw', options: { type: 'limbo' }}]}`
Server send back the file with the following headers:
![image](https://user-images.githubusercontent.com/29404633/68597090-5ce86500-046a-11ea-9456-9007ba857ce8.png)

The result is the following:
![image](https://user-images.githubusercontent.com/29404633/68597226-9ae58900-046a-11ea-9883-84035eacc7e3.png)

### Expected behaviour
Filepond should show signature.png in the component instead of c2lnbmF0dXJlLnBuZw

| Environment  | Version
|------------- | -----------
| OS           |  Linux Ubuntu
| Browser      | Chrome latest

Tested with react-filepond v5 and v7.0.1

**Comment by rikschennink** [comment]
Hi, which version of FilePond did you install `4.7.4`?

**Comment by Naghal** [comment]
Hi, I have core filepond ^4.0.0 as it is said in the changelog.md. Will give a try to 4.7.4

**Comment by rikschennink** [comment]
I can't reproduce this, a test case is very welcome.

**Comment by eivee** [comment]
Hi,  
I just ran into this problem myself today and couldn't figure out why the filename returned in the `Content-Disposition` header is not being picked up by Filepond.  
  
It turned out that the issue was not related to Filepond itself but to CORS. To resolve the problem all I had to do was send a `Access-Control-Expose-Headers: Content-Disposition` header with the response, that allows Filepond to read this header.  
  
### How to reproduce
1. Provide an initial files array with a temporary uploaded file
```jsx
<FilePond
  server="/api"
  files={[
    {
      source: 'serverSideSourceId',
      options: { type: 'limbo' }
    }
  ]}
/>
```

2. The file is now displayed with the filename `serverSideSourceId` in Filepond
3. Respond with the following headers from the `restore` endpoint on the server side when sending the file:
`/api?restore=serverSideSourceId`  
```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: *
Content-Type: text/plain
Content-Length: 42
Content-Disposition: inline; filename="expected-filename.txt"
```
4. The filename in Filepond remains `serverSideSourceId`

### Solution
1. Repeat steps 1-3 from above
2. In step 3, add the additional header `Access-Control-Expose-Headers: Content-Disposition` to the response
3. Filepond is now able to read the `Content-Disposition` header from the response (including the filename) and displays `expected-filename.txt` as expected

### Background
In a CORS environment, a client may only read the response headers that are considered *CORS-safelisted*. The `Content-Disposition` header is **not safelisted by default**. So in order to read that response header with a client, the server has to explicitly expose the header via CORS by including it in the `Access-Control-Expose-Headers` header.  
More info: [Access-Control-Expose-Headers - HTTP | MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers)

**Comment by rikschennink** [comment]
Thanks @eivee 🙏

I’ll close and refer to this issue as well:
https://github.com/pqina/filepond/issues/596
