### ISSUE TITLE
 styleButtonRemoveItemPosition=right"" hides text in file items

### ISSUE THREAD

**Issue by Obiwarn** [pqina/react-filepond#142]
The problem exists only for files that are already on the server.

![image](https://user-images.githubusercontent.com/9539797/86901069-64046780-c10c-11ea-80e5-109aef56dbcf.png)

**Comment by Obiwarn** [comment]
![image](https://user-images.githubusercontent.com/9539797/86901174-88604400-c10c-11ea-8db5-e7affaaca7c0.png)

**Comment by Obiwarn** [comment]
```
interface FileUploaderProps {
  filePondServer: FilePondFirebaseServer;
}
export function FileUploader(props: FileUploaderProps) {
  const [files, setFiles] = React.useState<any[]>();

  useEffect(() => {
    props.filePondServer.listFiles().then((files) => setFiles(files));
  }, [props.filePondServer]);

  return (
    <FilePond
      files={files}
      allowMultiple={true}
      maxFiles={100}
      server={props.filePondServer}
      styleButtonRemoveItemPosition="right"
      onUpdateFiles={(fileItems) => {
        setFiles(fileItems.map((fileItem) => fileItem.file));
      }}
      beforeRemoveFile={(file) => {
        return confirmAlertAsync(`Datei ${file.filename} löschen?`);
      }}
    />
  );
}
```

**Comment by rikschennink** [comment]
Please follow the issue template, it's right there in the text field when reporting a bug. Closed until the issue is updated.

---
**Describe the bug**
A clear and concise description of what the bug is.


**Logs**
Please include browser console and server logs around the time this bug occurred.


**To Reproduce**
To help us help you, if you've found a bug please consider the following:

* If you can demonstrate the bug, please do so by forking [this codesandbox](https://codesandbox.io/s/react-filepond-iwqq5).
* If that's not possible, we recommend creating a small repo that illustrates the problem.
* Reproductions should be [small, self-contained, correct examples](http://sscce.org).

Occasionally, this won't be possible, and that's fine – we still appreciate you raising the issue. But please understand that the more details you provide, the more inclined others are to help you out and the faster the issue can be resolved.

Please [format code snippets](https://help.github.com/articles/creating-and-highlighting-code-blocks/) using triple backticks and set the appropriate language.


**Expected behavior**
A clear and concise description of what you expected to happen.


**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

  Stack trace goes here...
</details>


**Information about your project:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 11)

- Your operating system: (e.x. MacOS 10, Ubuntu Linux 19.10, Windows 10, etc)

- FilePond version (Please check you can reproduce the issue with the latest release!)


**Additional context**
Add any other context about the problem here.
