### ISSUE TITLE
How get orderID or position in progress section

### ISSUE THREAD

**Issue by abadrangui** [pqina/react-filepond#155]
I'm using using FilePond with the firebase to upload photos. To list photos specific order, I need some fileposition or orderId to save photo datas. Pls help me.

For now i'm using orderID state to upload but I'm getting 2 files with same id
`
const Uploader = () => {
  const [files, setFiles] = useState([]);
  const [orderID, setOrderID] = useState(1.00);

  return (
    <FilePond
    ...rest

      server={{
        process: (_fieldName, file, _metadata, load, error, progress, _abort) => {
          ...rest
          const photoDoc = firestore.collection('photos').doc()
          const photoId = photoDoc.id
          photoDoc.set({
            filename: file.name,
            id: photoId,
            original: '',
            thumbnail: '',
            isReady: 0,
            fileSize: file.size,
            dimension: '', //end file in dimentioniig olj hiine
            zcode: albumZcode,
            orderID: orderID,
            price: albumPrice,
          }).then(() => {
            setOrderID(orderID + 1);

            const task = storage.ref(`private/${albumZcode}/${photoId}.jpeg`).put(file, {
              contentType: 'image/jpeg',
              customMetadata: {
                'zcode': albumZcode,
                'photoId': photoId,
              }
            });

            task.on('state_changed',
              snap => {
                progress(true, snap.bytesTransferred, snap.totalBytes);
              },
              err => {
                error(err.message);
              },
              () => {
                load(file.name);
                //   onRequestSave(id);
              }
            );
          })
        },
        ...
      }}

    />
  )
}
` 

Thanks in advance :)

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

If your issue can be classified as an integration question or a question about specific features of FilePond we ask you kindly to submit it on [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond).

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the template is not filled out or if the issue is determined to be a question.
