### ISSUE TITLE
Is fileRenameFunction available?

### ISSUE THREAD

**Issue by developdeez** [pqina/react-filepond#78]
Hey 

I was looking to see if I could use fileRenameFunction with this component?

Thanks

**Comment by rikschennink** [comment]
You’ll have to register the file-rename plugin and then it’s available

**Comment by developdeez** [comment]
Tried that:
import FilePondPluginFileRename from "filepond-plugin-file-rename";
registerPlugin(
  FilePondPluginFileRename
);

*Within my props for <FilePond>:
 allowFileRename={true}
      fileRenameFunction={file => {
        return `my_new_name${file.extension}`;
      }}

**Comment by rikschennink** [comment]
> Tried that:
> import FilePondPluginFileRename from "filepond-plugin-file-rename";
> registerPlugin(
> FilePondPluginFileRename
> );
> 
> *Within my props for FilePond component:
> allowFileRename={true}
> fileRenameFunction={file => {
> return `my_new_name${file.extension}`;
> }}

Please invest a couple minutes of your time and learn how to markup code in comments:
https://help.github.com/articles/creating-and-highlighting-code-blocks/

Is this with version 1.1.3, it works correctly here:
https://pqina.github.io/filepond-plugin-file-rename/

Any errors in console?

**Comment by developdeez** [comment]
I see that works just how I want.

Here are my versions:
 "filepond": "^3.7.1",
    "filepond-plugin-file-rename": "^1.1.3",

**Comment by rikschennink** [comment]
View source?

**Comment by developdeez** [comment]
@rikschennink that does show javacript I was interested in the react implementation. I think there may be a gap in functionality between the 2.

**Comment by developdeez** [comment]
Or if theres another way to override the file name? Im getting this when trying to loadmy image:
![image](https://user-images.githubusercontent.com/13059525/55201742-a9a05980-5181-11e9-86bf-cb1e53e74179.png)

**Comment by rikschennink** [comment]
See this codesandbox, works just fine:
https://codesandbox.io/s/r2mrno664

**Comment by berniegreen** [comment]
> See this codesandbox, works just fine:
> https://codesandbox.io/s/r2mrno664

Hi @rikschennink I tried out the sandbox you posted here and it will rename new files, but will not initial files. I forked your sandbox with my example here: [https://codesandbox.io/s/react-filepond-live-demo-forked-1fqyr?file=/src/index.js](url)

Am I forgetting something?

**Comment by rikschennink** [comment]
@berniegreen initial files should be given names with the `content-disposition` header.
https://pqina.nl/filepond/docs/patterns/api/server/#restore

**Comment by berniegreen** [comment]
@rikschennink thank you for getting back to me. I am using filepond completely front-end and just loading the images from URL links. I am using addFiles to set my files initially with useEffect. Check my sandbox above 

```
useEffect(() => {
    documentPond.current.addFiles(
      values[name][0] && [
        {
          source: values[name][0],
          options: { type: 'local' },
        },
      ]
    )
  }, [])
```


I have a custom process method that loads the files to S3, and it works fine. My custom load function works also except for the renaming part. I thought the plugin would be what was needed because S3 is already supplying the content-disposition header but it is not doing anything.

My custom load function looks like the below:
```
load: (source, load, error, progress, abort, headers) => {
    var request = new Request(source)
    fetch(request, { cache: 'reload' }).then((response) => {
      console.log(
        'OUTPUT: response',
        response.headers.get('Content-Disposition')
      )
      response.status === 200 &&
        response.blob().then((myBlob) => load(myBlob))
      response.status !== 200 && abort()
      response.status !== 200 && setFieldValue(name, [])
    })
  },
```

I can see the Content-Disposition is correct when logging the response headers. Looking at the file in network tab of chrome devtools the file shows Content-Disposition: inline; filename="my-file.pdf" and Access-Control-Expose-Headers: Content-Disposition, ETag

I am aware that I am not using filepond as it was intended but I have gotten everything to work so far the way I need it except for this part.

**Comment by rikschennink** [comment]
Hmm. FilePond only reads the content disposition header when it's in full control of the loading/processing of files. 

Can you try setting the `name` property on the `myBlob` variable and see if that updates the name?

```js
load: (source, load, error, progress, abort, headers) => {
    var request = new Request(source)
    fetch(request, { cache: 'reload' }).then((response) => {
      console.log(
        'OUTPUT: response',
        response.headers.get('Content-Disposition')
      )
      response.status === 200 &&
        response.blob().then((myBlob) => {

         // HERE
         myBlob.name = 'foo'

         load(myBlob))
      }
      response.status !== 200 && abort()
      response.status !== 200 && setFieldValue(name, [])
    })
  },
```

**Comment by berniegreen** [comment]
@rikschennink I tried the above and it still has the original file name displayed. I am using the `FilePondPluginGetFile` though, and when you hit the get file button it does download as the correct name set by `myBlob.name = 'foo'`.

**Comment by rikschennink** [comment]
Hi @berniegreen I just tried with this, and it shows 'foo.html' instead of 'index.html' on the file item in FilePond. I don't see a big difference but maybe I'm missing something?

```js
// Get a reference to the file input element
const inputElement = document.querySelector('input[type="file"]');

// Create the FilePond instance
const pond = FilePond.create(inputElement, {
    server: {
        load: (src, load) => {
            fetch(src)
                .then(res => res.blob())
                .then(blob => {
                    blob.name = 'foo.html';
                    load(blob);
                })
        }
    },
    files: [
        {
            source: './index.html',
            options: {
                type: 'local'
            }
        }
    ]
});
```

**Comment by berniegreen** [comment]
@rikschennink I tried your solution in my codesandbox and it works as expected.

I will have to solve my issue in my own codebase to figure out why it is not working there. The files show up as the original name still but when the component is remounted the foo.html shows up. Thank you for your help and I will figure out the rest as it doesn't look like the problem is related to filepond.
